import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";
import { HookedForm } from "@/components/HookedForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-stone-950 text-white">
        <div className="container flex flex-col justify-center gap-12 px-4 py-16 ">
          <div>
            <h1 className="text-4xl font-extrabold ">
              react-hook-form + TRPC example
            </h1>
          </div>
          <div className="flex flex-1">
            <HookedForm id={1} />
          </div>
        </div>
      </main>
    </>
  );
}
